version: "3.8"
services:
  app:
    image: ghcr.io/louis-cardon/finaltestlouis:develop
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mariadb
    env_file:
      - ./.env
    command: ["npm", "run", "start"]

  mariadb:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql
