version: "3.8"

services:
  app:
    image: ghcr.io/louis-cardon/finaltestlouis:latest
    environment:
      NODE_ENV: production
    networks:
      - frontend
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-http.rule=Host(`louis-cardon.alpex.ovh`)"
      - "traefik.http.routers.express-http.entrypoints=websecure"
      - "traefik.http.routers.express-http.tls.certresolver=myresolver"
    depends_on:
      - mariadb
    env_file:
      - ./.env
    command: ["npm", "run", "start"]

  mariadb:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
networks:
  frontend:
    external: true
    name: custom_frontend
  backend:
    external: true
    name: custom_backend